language: php

sudo: false

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    
before_script:
    - php -r "print_r(new \SoapClient('https://www.paypalobjects.com/wsdl/PayPalSvc.wsdl'));"

before_install:
    - composer self-update

install:
    - composer install

script:
    - ./vendor/bin/phpunit